# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'billing.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1250, 700)
        font = QtGui.QFont()
        font.setFamily("PibotoLt")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.camerawidget = QtWidgets.QWidget(self.centralwidget)
        self.camerawidget.setGeometry(QtCore.QRect(525, 10, 700, 600))
        self.camerawidget.setStyleSheet("#camerawidget {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#scanButton {\n"
"    border: 2px solid rgb(45, 134, 134); /* Border color */\n"
"    background-color: rgb(85, 255, 255); /* Button background color */\n"
"    border-radius: 10px; /* Round the corners */\n"
"    padding: 10px; /* Adjust padding for better look */\n"
"    outline: none;\n"
"}\n"
"\n"
"#scanButton:hover {\n"
"    background-color: rgb(65, 235, 235); /* Slightly darker on hover */\n"
"}\n"
"\n"
"#scanButton:pressed {\n"
"    background-color: rgb(45, 205, 205); /* Even darker when pressed */\n"
"}\n"
"")
        self.camerawidget.setObjectName("camerawidget")
        self.IdentityLabel = QtWidgets.QLabel(self.camerawidget)
        self.IdentityLabel.setGeometry(QtCore.QRect(200, 20, 291, 22))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setBold(True)
        font.setWeight(75)
        self.IdentityLabel.setFont(font)
        self.IdentityLabel.setObjectName("IdentityLabel")
        self.scanButton = QtWidgets.QPushButton(self.camerawidget)
        self.scanButton.setGeometry(QtCore.QRect(280, 550, 121, 41))
        font = QtGui.QFont()
        font.setFamily("PibotoLt")
        font.setBold(False)
        font.setWeight(50)
        self.scanButton.setFont(font)
        self.scanButton.setObjectName("scanButton")
        self.cameraLabel = QtWidgets.QLabel(self.camerawidget)
        self.cameraLabel.setGeometry(QtCore.QRect(80, 50, 500, 475))
        self.cameraLabel.setText("")
        self.cameraLabel.setObjectName("cameraLabel")
        self.billingWidget = QtWidgets.QWidget(self.centralwidget)
        self.billingWidget.setGeometry(QtCore.QRect(10, 10, 500, 600))
        self.billingWidget.setStyleSheet("#billingWidget {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#QtyButton {\n"
"    border: 2px solid rgb(45, 134, 134); /* Border color */\n"
"    background-color: rgb(85, 255, 255); /* Button background color */\n"
"    border-radius: 10px; /* Round the corners */\n"
"    padding: 10px; /* Adjust padding for better look */\n"
"    outline: none;\n"
"}\n"
"\n"
"#QtyButton:hover {\n"
"    background-color: rgb(65, 235, 235); /* Slightly darker on hover */\n"
"}\n"
"\n"
"#QtyButton:pressed {\n"
"    background-color: rgb(45, 205, 205); /* Even darker when pressed */\n"
"}\n"
"\n"
"#TotButton {\n"
"    border: 2px solid rgb(45, 134, 134); /* Border color */\n"
"    background-color: rgb(85, 255, 255); /* Button background color */\n"
"    border-radius: 10px; /* Round the corners */\n"
"    padding: 10px; /* Adjust padding for better look */\n"
"    outline: none;\n"
"}\n"
"\n"
"#TotButton:hover {\n"
"    background-color: rgb(65, 235, 235); /* Slightly darker on hover */\n"
"}\n"
"\n"
"#TotButton:pressed {\n"
"    background-color: rgb(45, 205, 205); /* Even darker when pressed */\n"
"}\n"
"\n"
"#FinishButton {\n"
"    border: 2px solid rgb(45, 134, 134); /* Border color */\n"
"    background-color: rgb(85, 255, 255); /* Button background color */\n"
"    border-radius: 10px; /* Round the corners */\n"
"    padding: 10px; /* Adjust padding for better look */\n"
"    outline: none;\n"
"}\n"
"\n"
"#FinishButton:hover {\n"
"    background-color: rgb(65, 235, 235); /* Slightly darker on hover */\n"
"}\n"
"\n"
"#FinishButton:pressed {\n"
"    background-color: rgb(45, 205, 205); /* Even darker when pressed */\n"
"}\n"
"")
        self.billingWidget.setObjectName("billingWidget")
        self.label = QtWidgets.QLabel(self.billingWidget)
        self.label.setGeometry(QtCore.QRect(210, 30, 91, 22))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.dateEdit = QtWidgets.QDateEdit(self.billingWidget)
        self.dateEdit.setGeometry(QtCore.QRect(20, 80, 112, 32))
        self.dateEdit.setObjectName("dateEdit")
        self.timeEdit = QtWidgets.QTimeEdit(self.billingWidget)
        self.timeEdit.setGeometry(QtCore.QRect(210, 80, 118, 32))
        self.timeEdit.setObjectName("timeEdit")
        self.tableWidget = QtWidgets.QTableWidget(self.billingWidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 150, 441, 151))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.QtyButton = QtWidgets.QPushButton(self.billingWidget)
        self.QtyButton.setGeometry(QtCore.QRect(20, 550, 111, 40))
        self.QtyButton.setObjectName("QtyButton")
        self.TotButton = QtWidgets.QPushButton(self.billingWidget)
        self.TotButton.setGeometry(QtCore.QRect(160, 550, 131, 40))
        self.TotButton.setObjectName("TotButton")
        self.FinishButton = QtWidgets.QPushButton(self.billingWidget)
        self.FinishButton.setGeometry(QtCore.QRect(320, 550, 101, 40))
        self.FinishButton.setObjectName("FinishButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1250, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.IdentityLabel.setText(_translate("MainWindow", "Identifying Item. Please Wait..."))
        self.scanButton.setText(_translate("MainWindow", "Scan Item"))
        self.label.setText(_translate("MainWindow", "Your Bill..."))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Total"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Item"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Price"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Qty"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Amount"))
        self.QtyButton.setText(_translate("MainWindow", "Increase Qty"))
        self.TotButton.setText(_translate("MainWindow", "Calculate Total"))
        self.FinishButton.setText(_translate("MainWindow", "Finish"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
